cd graphviz

emcc \
-I../extra/ \
../extra/typst_plugin.c \
../extra/Builtins.c \
../expat/expat/lib/xmltok_impl.c \
../expat/expat/lib/xmltok_ns.c \
../expat/expat/lib/xmlparse.c \
../expat/expat/lib/xmlrole.c \
../expat/expat/lib/xmltok.c \
-Ilib/cgraph \
lib/cgraph/imap.c \
lib/cgraph/io.c \
lib/cgraph/mem.c \
lib/cgraph/node.c \
lib/cgraph/obj.c \
lib/cgraph/pend.c \
lib/cgraph/rec.c \
lib/cgraph/refstr.c \
lib/cgraph/subg.c \
lib/cgraph/test_bitarray.c \
lib/cgraph/test_list.c \
lib/cgraph/test_stack.c \
lib/cgraph/test_tokenize.c \
lib/cgraph/utils.c \
lib/cgraph/write.c \
lib/cgraph/agerror.c \
lib/cgraph/apply.c \
lib/cgraph/attr.c \
lib/cgraph/edge.c \
lib/cgraph/graph.c \
lib/cgraph/id.c \
-Ilib/cdt \
lib/cdt/dtextract.c \
lib/cdt/dtflatten.c \
lib/cdt/dthash.c \
lib/cdt/dtlist.c \
lib/cdt/dtmethod.c \
lib/cdt/dtopen.c \
lib/cdt/dtrenew.c \
lib/cdt/dtrestore.c \
lib/cdt/dtsize.c \
lib/cdt/dtstat.c \
lib/cdt/dtstrhash.c \
lib/cdt/dttree.c \
lib/cdt/dtview.c \
lib/cdt/dtwalk.c \
lib/cdt/dtclose.c \
lib/cdt/dtdisc.c \
-Ilib/gvc \
lib/gvc/gvjobs.c \
lib/gvc/gvlayout.c \
lib/gvc/gvloadimage.c \
lib/gvc/gvplugin.c \
lib/gvc/gvrender.c \
lib/gvc/gvtextlayout.c \
lib/gvc/gvtool_tred.c \
lib/gvc/gvusershape.c \
lib/gvc/gvc.c \
lib/gvc/gvconfig.c \
lib/gvc/gvcontext.c \
lib/gvc/gvdevice.c \
lib/gvc/gvevent.c \
-Ilib/common \
lib/common/taper.c \
lib/common/textspan.c \
lib/common/textspan_lut.c \
lib/common/timing.c \
lib/common/utils.c \
lib/common/xml.c \
lib/common/args.c \
lib/common/arrows.c \
lib/common/colxlate.c \
lib/common/ellipse.c \
lib/common/emit.c \
lib/common/geom.c \
lib/common/globals.c \
lib/common/htmllex.c \
lib/common/htmltable.c \
lib/common/input.c \
lib/common/intset.c \
lib/common/labels.c \
lib/common/memory.c \
lib/common/ns.c \
lib/common/output.c \
lib/common/pointset.c \
lib/common/postproc.c \
lib/common/psusershape.c \
lib/common/routespl.c \
lib/common/shapes.c \
lib/common/splines.c \
-Ilib/label \
lib/label/xlabels.c \
lib/label/rectangle.c \
lib/label/split.q.c \
lib/label/index.c \
lib/label/node.c \
-Ilib/pathplan \
lib/pathplan/shortest.c \
lib/pathplan/util.c \
lib/pathplan/route.c \
lib/pathplan/solvers.c \
lib/xdot/xdot.c \
-Ilib/dotgen \
lib/dotgen/compound.c \
lib/dotgen/conc.c \
lib/dotgen/decomp.c \
lib/dotgen/dotinit.c \
lib/dotgen/dotsplines.c \
lib/dotgen/fastgr.c \
lib/dotgen/flat.c \
lib/dotgen/mincross.c \
lib/dotgen/position.c \
lib/dotgen/rank.c \
lib/dotgen/sameport.c \
lib/dotgen/acyclic.c \
lib/dotgen/aspect.c \
lib/dotgen/class1.c \
lib/dotgen/class2.c \
lib/dotgen/cluster.c \
-Ilib/ortho \
lib/ortho/trapezoid.c \
lib/ortho/fPQ.c \
lib/ortho/maze.c \
lib/ortho/ortho.c \
lib/ortho/partition.c \
lib/ortho/rawgraph.c \
lib/ortho/sgraph.c \
-Ilib/pack \
lib/pack/pack.c \
lib/pack/ccomps.c \
`#PLUGINS` \
plugin/dot_layout/gvplugin_dot_layout.c \
plugin/dot_layout/gvlayout_dot_layout.c \
plugin/core/gvrender_core_json.c \
plugin/core/gvrender_core_svg.c \
-Ilib \
-O2 \
-lm \
--target=wasm32-unknown-unknown \
-s ERROR_ON_UNDEFINED_SYMBOLS=0 \
-o dot.wasm \
-s STANDALONE_WASM=1 \
-s EXPORTED_FUNCTIONS=["_render"] \
--no-entry \

cd ..

wasm2wat ./graphviz/dot.wasm > Pre-patched-dot.wat

./Patch.sh

wat2wasm dot.wat > dot.wasm